2025-10-02 20:52:30,965 INFO    MainThread:14216 [wandb_init.py:setup_run_log_directory():705] Logging user logs to e:\PD1ModelTrainings\PD1ModelTrainingCodes\wandb\run-20251002_205230-4g94njrw\logs\debug.log
2025-10-02 20:52:30,965 INFO    MainThread:14216 [wandb_init.py:setup_run_log_directory():706] Logging internal logs to e:\PD1ModelTrainings\PD1ModelTrainingCodes\wandb\run-20251002_205230-4g94njrw\logs\debug-internal.log
2025-10-02 20:52:30,965 INFO    MainThread:14216 [wandb_init.py:monkeypatch_ipython():624] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001BEFEA9E520>
2025-10-02 20:52:30,965 INFO    MainThread:14216 [wandb_init.py:init():832] calling init triggers
2025-10-02 20:52:30,965 INFO    MainThread:14216 [wandb_init.py:init():837] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-10-02 20:52:32,550 INFO    MainThread:14216 [wandb_init.py:init():880] starting backend
2025-10-02 20:52:32,550 INFO    MainThread:14216 [wandb_init.py:init():883] sending inform_init request
2025-10-02 20:52:32,553 INFO    MainThread:14216 [wandb_init.py:init():891] backend started and connected
2025-10-02 20:52:32,559 INFO    MainThread:14216 [wandb_run.py:_label_probe_notebook():1330] probe notebook
2025-10-02 20:52:32,559 INFO    MainThread:14216 [wandb_run.py:_label_probe_notebook():1340] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-10-02 20:52:32,559 INFO    MainThread:14216 [wandb_init.py:init():961] updated telemetry
2025-10-02 20:52:32,613 INFO    MainThread:14216 [wandb_init.py:init():985] communicating run to backend with 90.0 second timeout
2025-10-02 20:52:33,270 INFO    MainThread:14216 [wandb_init.py:init():1036] starting run threads in backend
2025-10-02 20:52:33,476 INFO    MainThread:14216 [wandb_run.py:_console_start():2506] atexit reg
2025-10-02 20:52:33,476 INFO    MainThread:14216 [wandb_run.py:_redirect():2354] redirect: wrap_raw
2025-10-02 20:52:33,476 INFO    MainThread:14216 [wandb_run.py:_redirect():2423] Wrapping output streams.
2025-10-02 20:52:33,476 INFO    MainThread:14216 [wandb_run.py:_redirect():2446] Redirects installed.
2025-10-02 20:52:33,478 INFO    MainThread:14216 [wandb_init.py:init():1076] run started, returning control to user process
2025-10-02 20:52:33,855 INFO    MainThread:14216 [wandb_init.py:_post_run_cell_hook():594] [no run ID] resuming backend
2025-10-02 20:53:01,175 INFO    MainThread:14216 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-10-02 20:53:01,175 INFO    MainThread:14216 [wandb_init.py:_pre_run_cell_hook():583] [no run ID] pausing backend
2025-10-02 20:53:08,565 INFO    MainThread:14216 [wandb_init.py:_post_run_cell_hook():594] [no run ID] resuming backend
2025-10-02 20:53:20,628 INFO    MainThread:14216 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-10-02 20:53:20,628 INFO    MainThread:14216 [wandb_init.py:_pre_run_cell_hook():583] [no run ID] pausing backend
2025-10-02 20:53:20,642 INFO    MainThread:14216 [wandb_run.py:_finish():2272] finishing run eryyyj-technological-institute-of-the-philippines/pd1training/4g94njrw
2025-10-02 20:53:20,643 INFO    MainThread:14216 [jupyter.py:save_history():480] not saving jupyter history
2025-10-02 20:53:20,643 INFO    MainThread:14216 [jupyter.py:save_ipynb():404] not saving jupyter notebook
2025-10-02 20:53:20,643 INFO    MainThread:14216 [wandb_init.py:_jupyter_teardown():609] cleaning up jupyter logic
2025-10-02 20:53:20,643 INFO    MainThread:14216 [wandb_run.py:_atexit_cleanup():2471] got exitcode: 0
2025-10-02 20:53:20,643 INFO    MainThread:14216 [wandb_run.py:_restore():2453] restore
2025-10-02 20:53:20,644 INFO    MainThread:14216 [wandb_run.py:_restore():2459] restore done
2025-10-02 20:53:22,222 INFO    MainThread:14216 [wandb_run.py:_footer_sync_info():3869] logging synced files
